export const homeData = [
  {
    id: 1,
    name: "Dune",
    rating: 4.7,
    time: "2h : 35mins",
    desc: "Dune raconte l'histoire d'un jeune homme brillant et doué au destin plus grand que lui-même, devant se rendre sur la planète la plus dangereuse de l'univers afin d'assurer l'avenir de sa famille et de son peuple.",
    starring: "Timothée Chamalet, Zendaya",
    genres: "Action",
    tags: "Action, Aventure, Horreur",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "15-Sept-2021",
  },
  {
    id: 2,
    name: "Nevertheless",
    rating: 4.6,
    time: "10 épisodes",
    desc: "Yu Na Bi est étudiante en arts. Depuis sa rupture douloureuse avec son premier amour infidèle, elle ne croit plus en l'amour. Cependant, lorsqu'elle rencontre Park Jae Eon, ses barrières semblent se briser une par une. ",
    starring: "Song Kang, Han So Hee",
    genres: "Série Coréenne",
    tags: "Romance, Drame ",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "18-Juin-2021",
  },
  {
    id: 3,
    name: "Black Butler",
    rating: 4.8,
    time: "24 épisodes",
    desc: "Ciel Phantomhive est un comte de douze ans, vivant dans un immense manoir perdu dans la campagne de Londres. S'il arrive à gérer la compagnie de fabrication de jouets et de confiseries léguée par ses aïeuls, c'est sans doute car il est efficacement secondé par Sebastian, son majordome. Majordome qui n'est autre qu'un démon avec qui il a fait un pacte...  ",
    starring: "Toboso Yana",
    genres: "Seinen",
    tags: "Drame, Surnaturel, Psychologique ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "16-Sept-2006",
  },
  {
    id: 4,
    name: "Mercredi",
    rating: 4.9,
    time: "1 saison",
    desc: "Brillante, sarcastique et un peu morte à l'intérieur, Mercredi Addams enquête sur une série de crimes tout en se faisant des amis (et des ennemis) à l'Académie Nevermore.",
    starring: "Jenna Ortega, Gwendoline Christie, Riki Lindhome",
    genres: "Fantastique",
    tags: "Surnaturel, horrifique ",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "23-Nov-2022",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Avatar 2",
    time: "3h : 12mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Super Mario Bros",
    time: "1h : 45mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Glitch",
    time: "1 saison",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Le Chat Potté 2",
    time: "1h : 40mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Hell's Paradise",
    time: "1 saison",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "1899",
    time: "2h : 52 minutes",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "Move to Heaven",
    time: "10 épisodes",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Avatar 2",
    time: "3h : 12mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Hell's Paradise",
    time: "1 saison",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Le Chat Potté 2",
    time: "1h : 40mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "Jurassic World",
    rating: 4.7,
    time: "2h : 26mins",
    desc: "Les dinosaures font désormais partie du quotidien de l'humanité entière. Un équilibre fragile qui va remettre en question la domination de l'espèce humaine maintenant qu'elle doit partager son espace avec les créatures les plus féroces que l'histoire ait jamais connues.",
    starring: "Chris Pratt, Bryce Dallas Howard, Laura Dern",
    genres: "Action",
    tags: "Aventure, Science fiction",
    cover: "../images/img/slide1.png",
    video: "../video/video5.mp4",
    date: "8-Juin-2022",
  },
  {
    id: 2,
    name: "Stranger Things",
    rating: 4.6,
    time: "34 épisodes",
    desc: "En 1983, à Hawkins dans l'Indiana, Will Byers disparaît de son domicile. Ses amis se lancent alors dans une recherche semée d'embûches pour le retrouver. Pendant leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. ",
    starring: "Millie Bobby Brown, Finn Wolfhard, Noah Schnapp, Caleb McLaughlin, Gaten Matarazzo",
    genres: "Fantastique",
    tags: "Drame, Thriller, science-fiction",
    cover: "../images/img/slide2.jpg",
    video: "../video/video6.mp4",
    date: "15-Juillet-2016",
  },
  {
    id: 3,
    name: "Ready Player One",
    rating: 4.8,
    time: "2h : 20mins",
    desc: "En 2045, la planète frôle le chaos et s'effondre, mais les gens trouvent du réconfort dans l'OASIS, un monde virtuel créé par James Halliday. Lorsque ce dernier décède, il promet immense fortune à la première personne qui découvrira l'oeuf de Pâques numérique caché.  ",
    starring: "Tye Sheridan, Olivia Cooke, Ben Mendelsohn",
    genres: "Fantastique",
    tags: "Aventure, Science-fiction",
    cover: "../images/img/slide3.jpg",
    video: "../video/video7.mp4",
    date: "28-Mars-2018",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "Rick et Morty",
    time: "6 saisons",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Your name",
    time: "1h : 52mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "Une porte pour l'été",
    time: "1h : 58mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "The In Between",
    time: "1h : 56mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Glitch",
    time: "1 saison",
  },
]
